# version: '3'

services:
  rabbit-m:
    container_name: nameko-example-rabbitmq-m
    image: rabbitmq:3.7-management
    ports:
      - "15677:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql-m:
    container_name: nameko-example-mysql-m
    image: mysql:5.7
    ports:
      - "3309:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "moovby_driverless_jakarta"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
  
  transport-m:
    build: ./transport
    container_name: nameko-example-transport-m
    depends_on:
      - rabbit-m
      - mysql-m
    ports:
      - "9005:8000"
    links:
      - "rabbit-m:nameko-example-rabbitmq-m"
      - "mysql-m:nameko-example-mysql-m"
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_HOST: "nameko-example-mysql-m"
      MYSQL_DB: "moovby_driverless_jakarta"
      RABBIT_HOST: "rabbit-m"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
    
  gateway-m:
    build: ./gateway
    container_name: nameko-example-gateway-m
    depends_on:
      - rabbit-m
    ports:
      - "8005:8000"
    links:
      - "rabbit-m:nameko-example-rabbitmq-m"
    environment:
      RABBIT_HOST: "rabbit-m"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

volumes:
  mysql_data:
    driver: local