AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

MYSQL_URI_M: mysql://user:${MYSQL_PASSWORD:""}@${MYSQL_HOST:localhost}:${MYSQL_PORT:3311}/${MYSQL_DB:moovby_driverless_jakarta}