# version: '3'

services:
  rabbit-j:
    container_name: nameko-example-rabbitmq-j
    image: rabbitmq:3.7-management
    ports:
      - "15676:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql-j:
    container_name: nameko-example-mysql-j
    image: mysql:5.7
    ports:
      - "3310:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "jayamahe_easy_ride_jakarta"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  transport-j:
    build: ./transport
    container_name: nameko-example-transport-j
    depends_on:
      - rabbit-j
      - mysql-j
    ports:
      - "9004:8000"
    links:
      - "rabbit-j:nameko-example-rabbitmq-j"
      - "mysql-j:nameko-example-mysql-j"
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_HOST: "nameko-example-mysql-j"
      MYSQL_DB: "jayamahe_easy_ride_jakarta"
      RABBIT_HOST: "rabbit-j"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
    
  gateway-j:
    build: ./gateway
    container_name: nameko-example-gateway-j
    depends_on:
      - rabbit-j
    ports:
      - "8004:8000"
    links:
      - "rabbit-j:nameko-example-rabbitmq-j"
    environment:
      RABBIT_HOST: "rabbit-j"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
  
volumes:
  mysql_data:
    driver: local
