# version: '3'

services:
  rabbit-ak:
    container_name: nameko-example-rabbitmq-ak
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql-ak:
    container_name: nameko-example-mysql-ak
    image: mysql:5.7
    ports:
      - "33013:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "ada_kawan_jogja"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  transport-ak:
    build: ./transport
    container_name: nameko-example-transport-ak
    depends_on:
      - rabbit-ak
      - mysql-ak
    ports:
      - "9001:8000"
    links:
      - "rabbit-ak:nameko-example-rabbitmq-ak"
      - "mysql-ak:nameko-example-mysql-ak"
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_HOST: "nameko-example-mysql-ak"
      MYSQL_DB: "ada_kawan_jogja"
      RABBIT_HOST: "rabbit-ak"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
    
  gateway-ak:
    build: ./gateway
    container_name: nameko-example-gateway-ak
    depends_on:
      - rabbit-ak
    ports:
      - "8001:8000"
    links:
      - "rabbit-ak:nameko-example-rabbitmq-ak"
    environment:
      RABBIT_HOST: "rabbit-ak"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

volumes:
  mysql_data:
    driver: local