# version: '3'

services:
  rabbit:
    container_name: nameko-example-rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - "15673:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql-p:
    container_name: nameko-example-mysql-p
    image: mysql:5.7
    ports:
      - "3308:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "puri_bali"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  transport-p:
    build: ./transport
    container_name: nameko-example-transport-p
    depends_on:
      - rabbit
      - mysql-p
    ports:
      - "9006:8000"
    links:
      - "rabbit:nameko-example-rabbitmq"
      - "mysql-p:nameko-example-mysql-p"
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_HOST: "nameko-example-mysql-p"
      MYSQL_DB: "puri_bali"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
    
  gateway-p:
    build: ./gateway
    container_name: nameko-example-gateway-p
    depends_on:
      - rabbit
    ports:
      - "8006:8000"
    links:
      - "rabbit:nameko-example-rabbitmq"
    environment:
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

volumes:
  mysql_data:
    driver: local