# version: '3'

services:
  rabbit-a:
    container_name: nameko-example-rabbitmq-a
    image: rabbitmq:3.7-management
    ports:
      - "15674:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql-a:
    container_name: nameko-example-mysql-a
    image: mysql:5.7
    ports:
      - "33012:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "arasya_jakarta"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  transport-a:
    build: ./transport
    container_name: nameko-example-transport-a
    depends_on:
      - rabbit-a
      - mysql-a
    ports:
      - "9002:8000"
    links:
      - "rabbit-a:nameko-example-rabbitmq-a"
      - "mysql-a:nameko-example-mysql-a"
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_HOST: "nameko-example-mysql-a"
      MYSQL_DB: "arasya_jakarta"
      RABBIT_HOST: "rabbit-a"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
    
  gateway-a:
    build: ./gateway
    container_name: nameko-example-gateway-a
    depends_on:
      - rabbit-a
    ports:
      - "8002:8000"
    links:
      - "rabbit-a:nameko-example-rabbitmq-a"
    environment:
      RABBIT_HOST: "rabbit-a"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"