# version: '3'

services:
  rabbit-er:
    container_name: nameko-example-rabbitmq-er
    image: rabbitmq:3.7-management
    ports:
      - "15675:15672" # Exposing RabbitMQ web management on different port for convenience
    restart: always

  mysql-er:
    container_name: nameko-example-mysql-er
    image: mysql:5.7
    ports:
      - "33011:3306" # Exposing MySQL on different port for convenience
    environment:
      MYSQL_DATABASE: "empat_roda_jogja"
      MYSQL_ROOT_PASSWORD: "admin"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

  transport-er:
    build: ./transport
    container_name: nameko-example-transport-er
    depends_on:
      - rabbit-er
      - mysql-er
    ports:
      - "9003:8000"
    links:
      - "rabbit-er:nameko-example-rabbitmq-er"
      - "mysql-er:nameko-example-mysql-er"
    environment:
      MYSQL_PASSWORD: "admin"
      MYSQL_HOST: "nameko-example-mysql-er"
      MYSQL_DB: "empat_roda_jogja"
      RABBIT_HOST: "rabbit-er"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"
    
  gateway-er:
    build: ./gateway
    container_name: nameko-example-gateway-er
    depends_on:
      - rabbit-er
    ports:
      - "8003:8000"
    links:
      - "rabbit-er:nameko-example-rabbitmq-er"
    environment:
      RABBIT_HOST: "rabbit-er"
      RABBIT_PORT: "5672"
      RABBIT_USER: "guest"
      RABBIT_PASSWORD: "guest"
      RABBIT_MANAGEMENT_PORT: "15672"

 